<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Client extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Client_model');
    } 

    /*
     * Listing of tb_am_clients
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('tb_am_client/index?');
        $config['total_rows'] = $this->Client_model->get_all_tb_am_clients_count();
        $this->pagination->initialize($config);

        $data['tb_am_clients'] = $this->Client_model->get_all_tb_am_clients($params);
        
        $data['_view'] = 'client/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tb_am_client
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('client_email','Client Email','is_unique[tb_am_clients.client_email]|valid_email');
		$this->form_validation->set_rules('client_fullname','Client Fullname','required');
		$this->form_validation->set_rules('client_type','Client Type','required');
		$this->form_validation->set_rules('client_phone','Client Phone','is_unique[tb_am_clients.client_phone]');
		
		if($this->form_validation->run())     
        {   
            $current_datetime=date('Y-m-d H::s');

            $params = array(
				'client_fullname' => $this->input->post('client_fullname'),
				'client_email' => $this->input->post('client_email'),
				'client_profession' => $this->input->post('client_profession'),
				'client_type' => $this->input->post('client_type'),
				'client_phone' => $this->input->post('client_phone'),
				'client_created' => $current_datetime,
				'client_adresse' => $this->input->post('client_adresse'),
            );
            
            $tb_am_client_id = $this->Client_model->add_tb_am_client($params);
            redirect('client/index');
        }
        else
        {            
            $data['_view'] = 'client/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tb_am_client
     */
    function edit($client_id)
    {   
        // check if the tb_am_client exists before trying to edit it
        $data['tb_am_client'] = $this->Client_model->get_tb_am_client($client_id);
        
        if(isset($data['tb_am_client']['client_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('client_email','Client Email','valid_email');
        $this->form_validation->set_rules('client_fullname','Client Fullname','required');
        $this->form_validation->set_rules('client_type','Client Type','required');
        $this->form_validation->set_rules('client_phone','Client Phone','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'client_fullname' => $this->input->post('client_fullname'),
					'client_email' => $this->input->post('client_email'),
					'client_profession' => $this->input->post('client_profession'),
					'client_type' => $this->input->post('client_type'),
					'client_phone' => $this->input->post('client_phone'),
					'client_adresse' => $this->input->post('client_adresse'),
                );

                $this->Client_model->update_tb_am_client($client_id,$params);            
                redirect('client/index');
            }
            else
            {
                $data['_view'] = 'client/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tb_am_client you are trying to edit does not exist.');
    } 

    /*
     * Deleting tb_am_client
     */
    function remove($client_id)
    {
        $tb_am_client = $this->Client_model->get_tb_am_client($client_id);

        // check if the tb_am_client exists before trying to delete it
        if(isset($tb_am_client['client_id']))
        {
            $this->Client_model->delete_tb_am_client($client_id);
            redirect('client/index');
        }
        else
            show_error('The tb_am_client you are trying to delete does not exist.');
    }
    
}
