<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Agence_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tb_am_agence by agence_id
     */
    function get_tb_am_agence($agence_id)
    {
        return $this->db->get_where('tb_am_agences',array('agence_id'=>$agence_id))->row_array();
    }
    
    /*
     * Get all tb_am_agences count
     */
    function get_all_tb_am_agences_count()
    {
        $this->db->from('tb_am_agences');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all tb_am_agences
     */
    function get_all_tb_am_agences($params = array())
    {
        $this->db->order_by('agence_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('tb_am_agences')->result_array();
    }
        
    /*
     * function to add new tb_am_agence
     */
    function add_tb_am_agence($params)
    {
        $this->db->insert('tb_am_agences',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tb_am_agence
     */
    function update_tb_am_agence($agence_id,$params)
    {
        $this->db->where('agence_id',$agence_id);
        return $this->db->update('tb_am_agences',$params);
    }
    
    /*
     * function to delete tb_am_agence
     */
    function delete_tb_am_agence($agence_id)
    {
        return $this->db->delete('tb_am_agences',array('agence_id'=>$agence_id));
    }
}
