<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Client_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tb_am_client by client_id
     */
    function get_tb_am_client($client_id)
    {
        return $this->db->get_where('tb_am_clients',array('client_id'=>$client_id))->row_array();
    }
    
    /*
     * Get all tb_am_clients count
     */
    function get_all_tb_am_clients_count()
    {
        $this->db->from('tb_am_clients');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all tb_am_clients
     */
    function get_all_tb_am_clients($params = array())
    {
        $this->db->order_by('client_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('tb_am_clients')->result_array();
    }
        
    /*
     * function to add new tb_am_client
     */
    function add_tb_am_client($params)
    {
        $this->db->insert('tb_am_clients',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tb_am_client
     */
    function update_tb_am_client($client_id,$params)
    {
        $this->db->where('client_id',$client_id);
        return $this->db->update('tb_am_clients',$params);
    }
    
    /*
     * function to delete tb_am_client
     */
    function delete_tb_am_client($client_id)
    {
        return $this->db->delete('tb_am_clients',array('client_id'=>$client_id));
    }
}
