<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Transaction_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
     // jointure de tables entre visiteur - departement - statut
    public function get_join_depots($params = array())
    {
        //return $this->db->get('tb_am_transactions')->result_array();
    
        //$this->db->limit(5);
        $this->db->order_by('tb_am_transactions.transac_id', 'DESC');
        $this->db->join('tb_am_clients', 'tb_am_clients.client_id = tb_am_transactions.client_sid');
        $this->db->join('tb_am_agences', 'tb_am_agences.agence_id = tb_am_transactions.provenance');


        //$this->db->join('tb_am_clients', 'tb_am_clients.client_id = tb_am_transactions.beneficiaire_sid');
        //$this->db->join('tb_am_agences', 'tb_am_agences.agence_id = tb_am_transactions.destination');

        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        
        $query = $this->db->get('tb_am_transactions');
    
        return $query->result();
    }

      // jointure de tables entre visiteur - departement - statut
    public function get_join_retraits($params = array())
    {
        //return $this->db->get('tb_am_transactions')->result_array();
    
        //$this->db->limit(5);
        $this->db->order_by('tb_am_transactions.transac_id', 'DESC');
        $this->db->join('tb_am_clients', 'tb_am_clients.client_id = tb_am_transactions.beneficiaire_sid');
        $this->db->join('tb_am_agences', 'tb_am_agences.agence_id = tb_am_transactions.destination');

        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        
        $query = $this->db->get('tb_am_transactions');
    
        return $query->result();
    }
    /*
     * Get tb_am_transaction by transac_id
     */
    function get_tb_am_transaction($transac_id)
    {
        return $this->db->get_where('tb_am_transactions',array('transac_id'=>$transac_id))->row_array();
    }
    
    /*
     * Get all tb_am_transactions count
     */
    function get_all_tb_am_transactions_count()
    {
        $this->db->from('tb_am_transactions');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all tb_am_transactions
     */
    function get_all_tb_am_transactions($params = array())
    {
        $this->db->order_by('transac_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('tb_am_transactions')->result_array();
    }
        
    /*
     * function to add new tb_am_transaction
     */
    function add_tb_am_transaction($params)
    {
        $this->db->insert('tb_am_transactions',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tb_am_transaction
     */
    function update_tb_am_transaction($transac_id,$params)
    {
        $this->db->where('transac_id',$transac_id);
        return $this->db->update('tb_am_transactions',$params);
    }
    
    /*
     * function to delete tb_am_transaction
     */
    function delete_tb_am_transaction($transac_id)
    {
        return $this->db->delete('tb_am_transactions',array('transac_id'=>$transac_id));
    }
}
